---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- import_tasks: preflight.yml

- import_tasks: confgiure.yml
  when: state == 'present'

- import_tasks: install.yml
  when: state == 'present'

- name: Uninstall package
  become: true
  package:
    name: fahclient
    state: absent
  when: state == 'absent'
